version: '2'

services:
  app:
    image: iraola-challenge-image:latest
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/challenge-db
      - SPRING_DATASOURCE_USERNAME=challenge-db
      - SPRING_DATASOURCE_PASSWORD=challenge-db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13.1-alpine
    container_name: db
    volumes:
      - ~/.challenge-image/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=challenge-db
      - POSTGRES_PASSWORD=challenge-db